### ISSUE TITLE
majesty-diffusion: fix prompt parsing with ':' in it

### ISSUE THREAD

**Issue by nielsrolf** [pollinations/majesty-diffusion-cog#1]

**Comment by nielsrolf** [comment]
```
[ec2-user@ip-10-0-62-4 ~]$ cat /tmp/ipfs/input/text_prompt 
"  rmix The go-to platform for designing, selling, and collecting 3D digital wearables for the metaverse. using model: Disco Diffusion."[ec2-user@ip-10-0-62-4 ~]$ cat /tmp/ipfs/output/log
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - RN50]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - RN101]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - RN50x4]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - RN50x16]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - RN50x64]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - ViT-B/32]
2022-08-01 12:42:28.088 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - ViT-B/16]
2022-08-01 12:42:28.089 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - ViT-L/14]
2022-08-01 12:42:28.089 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - openai - ViT-L/14@336px]
2022-08-01 12:42:28.653 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50', {})
2022-08-01 12:42:28.653 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50--openai]
2022-08-01 12:42:28.653 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50', {})
2022-08-01 12:42:28.654 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50--yfcc15m]
2022-08-01 12:42:28.654 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50', {})
2022-08-01 12:42:28.654 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50--cc12m]
2022-08-01 12:42:28.654 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50-quickgelu', {})
2022-08-01 12:42:28.654 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50-quickgelu--openai]
2022-08-01 12:42:28.654 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50-quickgelu', {})
2022-08-01 12:42:28.654 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50-quickgelu--yfcc15m]
2022-08-01 12:42:28.654 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50-quickgelu', {})
2022-08-01 12:42:28.655 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50-quickgelu--cc12m]
2022-08-01 12:42:28.655 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN101', {})
2022-08-01 12:42:28.655 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN101--openai]
2022-08-01 12:42:28.655 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN101', {})
2022-08-01 12:42:28.655 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN101--yfcc15m]
2022-08-01 12:42:28.655 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN101-quickgelu', {})
2022-08-01 12:42:28.655 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN101-quickgelu--openai]
2022-08-01 12:42:28.656 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN101-quickgelu', {})
2022-08-01 12:42:28.656 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN101-quickgelu--yfcc15m]
2022-08-01 12:42:28.656 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50x4', {})
2022-08-01 12:42:28.656 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50x4--openai]
2022-08-01 12:42:28.656 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50x16', {})
2022-08-01 12:42:28.656 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50x16--openai]
2022-08-01 12:42:28.656 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('RN50x64', {})
2022-08-01 12:42:28.656 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - RN50x64--openai]
2022-08-01 12:42:28.656 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32--openai]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32--laion2b_e16]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32--laion400m_e31]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32--laion400m_e32]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32-quickgelu', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32-quickgelu--openai]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32-quickgelu', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32-quickgelu--laion400m_e31]
2022-08-01 12:42:28.657 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-32-quickgelu', {})
2022-08-01 12:42:28.657 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-32-quickgelu--laion400m_e32]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-16', {})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-16--openai]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-16', {})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-16--laion400m_e31]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-16', {})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-16--laion400m_e32]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-16-plus-240', {'input_resolution': 240})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-16-plus-240--laion400m_e31]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-B-16-plus-240', {'input_resolution': 240})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-B-16-plus-240--laion400m_e32]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-L-14', {})
2022-08-01 12:42:28.658 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-L-14--openai]
2022-08-01 12:42:28.658 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-L-14', {})
2022-08-01 12:42:28.659 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-L-14--laion400m_e31]
2022-08-01 12:42:28.659 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-L-14', {})
2022-08-01 12:42:28.659 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-L-14--laion400m_e32]
2022-08-01 12:42:28.659 | DEBUG    | mmc.loaders.mlfcliploader:<module>:78 - ('ViT-L-14-336', {})
2022-08-01 12:42:28.659 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - mlfoundations - ViT-L-14-336--openai]
2022-08-01 12:42:28.660 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - sbert - ViT-B-32-multilingual-v1]
2022-08-01 12:42:28.661 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - sajjjadayobi - clipfa]
2022-08-01 12:42:28.679 | DEBUG    | napm.config:config_path:28 - /root/.cache/napm/config.yaml
2022-08-01 12:42:28.686 | DEBUG    | napm.config:config_path:28 - /root/.cache/napm/config.yaml
2022-08-01 12:42:28.708 | DEBUG    | mmc.registry:register_model:38 - registering model: [cloob - crowsonkb - cloob_laion_400m_vit_b_16_16_epochs]
2022-08-01 12:42:28.708 | DEBUG    | mmc.registry:register_model:38 - registering model: [cloob - crowsonkb - cloob_laion_400m_vit_b_16_32_epochs]
2022-08-01 12:42:28.709 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - navervision - kelip_ViT-B/32]
2022-08-01 12:42:28.711 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - facebookresearch - clip_small_25ep]
2022-08-01 12:42:28.711 | DEBUG    | mmc.registry:register_model:38 - registering model: [simclr - facebookresearch - simclr_small_25ep]
2022-08-01 12:42:28.711 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_small_25ep]
2022-08-01 12:42:28.711 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_small_50ep]
2022-08-01 12:42:28.711 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_small_100ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - facebookresearch - clip_base_25ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [simclr - facebookresearch - simclr_base_25ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_base_25ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_base_50ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_base_100ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - facebookresearch - clip_large_25ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [simclr - facebookresearch - simclr_large_25ep]
2022-08-01 12:42:28.712 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_large_25ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_large_50ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_large_100ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - facebookresearch - clip_base_cc3m_40ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_base_cc3m_40ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [clip - facebookresearch - clip_base_cc12m_35ep]
2022-08-01 12:42:28.713 | DEBUG    | mmc.registry:register_model:38 - registering model: [slip - facebookresearch - slip_base_cc12m_35ep]
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /root/.cache/torch/hub/checkpoints/vgg16-397923af.pth
100%|██████████| 528M/528M [00:02<00:00, 189MB/s]  
Loading model from: /root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/lpips/weights/v0.1/vgg.pth
INFO:     Started server process [1]
INFO:     Waiting for application startup.
Loading model from /content/models//latent_diffusion_txt2img_f8_large.ckpt
finetuned
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 873.28 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Downloading: 100%|██████████| 28.0/28.0 [00:00<00:00, 18.5kB/s]
Downloading: 100%|██████████| 226k/226k [00:00<00:00, 43.8MB/s]
Downloading: 100%|██████████| 455k/455k [00:00<00:00, 34.6MB/s]
Downloading: 100%|██████████| 570/570 [00:00<00:00, 641kB/s]
Loaded  ViT-B-16--openai
100%|████████████████████████████████████████| 351M/351M [00:01<00:00, 312MiB/s]
Loaded  ViT-L-14--openai
100%|████████████████████████████████████████| 933M/933M [00:07<00:00, 133MiB/s]
Loaded  ViT-B-32--laion2b_e16
100%|████████████████████████████████████████| 605M/605M [00:05<00:00, 103MiB/s]
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
Sampling:   0%|          | 0/1 [00:00<?, ?it/s]Sampling images 1/1
Sampling: 100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
INFO:     172.17.0.1:47120 - "POST /predictions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/routing.py", line 228, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/cog/server/http.py", line 79, in predict
    output = predictor.predict(**request.input.dict())
  File "predict.py", line 768, in predict
    txt, weight = parse_prompt(prompt)
  File "predict.py", line 231, in parse_prompt
    return vals[0], float(vals[1])
ValueError: could not convert string to float: ' Disco Diffusion.'
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/routing.py", line 228, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/to_thread.py", line 32, in run_sync
    func, *args, cancellable=cancellable, limiter=limiter
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/cog/server/http.py", line 79, in predict
    output = predictor.predict(**request.input.dict())
  File "predict.py", line 768, in predict
    txt, weight = parse_prompt(prompt)
  File "predict.py", line 231, in parse_prompt
    return vals[0], float(vals[1])
ValueError: could not convert string to float: ' Disco Diffusion.'
```
